INFO 2023-08-29 19:46:19,351 autoreload 13000 16492 Watching for file changes with StatReloader
INFO 2023-08-29 19:46:20,264 basehttp 13000 2876 "GET / HTTP/1.1" 200 13
INFO 2023-08-29 19:46:34,490 basehttp 13000 2876 "GET /sem_1_app_2/heads_tails/ HTTP/1.1" 200 8
INFO 2023-08-29 19:46:39,105 basehttp 13000 2876 "GET /sem_1_app_2/cube HTTP/1.1" 301 0
INFO 2023-08-29 19:46:39,110 basehttp 13000 19860 "GET /sem_1_app_2/cube/ HTTP/1.1" 200 1
INFO 2023-08-29 19:46:40,852 basehttp 13000 19860 "GET /sem_1_app_2/cube/ HTTP/1.1" 200 1
INFO 2023-08-29 19:46:41,003 basehttp 13000 19860 "GET /sem_1_app_2/cube/ HTTP/1.1" 200 1
INFO 2023-08-29 19:46:41,120 basehttp 13000 19860 "GET /sem_1_app_2/cube/ HTTP/1.1" 200 1
INFO 2023-08-29 19:46:45,036 basehttp 13000 19860 "GET /sem_1_app_2/heads_tails/ HTTP/1.1" 200 8
INFO 2023-08-29 19:46:46,426 basehttp 13000 19860 "GET /sem_1_app_2/heads_tails/ HTTP/1.1" 200 10
INFO 2023-08-29 19:46:46,855 basehttp 13000 19860 "GET /sem_1_app_2/heads_tails/ HTTP/1.1" 200 8
INFO 2023-08-29 19:46:47,348 basehttp 13000 19860 "GET /sem_1_app_2/heads_tails/ HTTP/1.1" 200 8
INFO 2023-08-29 19:46:47,694 basehttp 13000 19860 "GET /sem_1_app_2/heads_tails/ HTTP/1.1" 200 8
INFO 2023-08-29 19:46:48,292 basehttp 13000 19860 "GET /sem_1_app_2/heads_tails/ HTTP/1.1" 200 8
INFO 2023-08-29 19:46:48,643 basehttp 13000 19860 "GET /sem_1_app_2/heads_tails/ HTTP/1.1" 200 10
WARNING 2023-08-29 19:46:53,365 log 13000 19860 Not Found: /sem_1_app_2/rand_naum
WARNING 2023-08-29 19:46:53,366 basehttp 13000 19860 "GET /sem_1_app_2/rand_naum HTTP/1.1" 404 2863
INFO 2023-08-29 19:46:56,842 basehttp 13000 19860 "GET /sem_1_app_2/rand_num HTTP/1.1" 301 0
INFO 2023-08-29 19:46:56,849 basehttp 13000 17488 "GET /sem_1_app_2/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-29 19:46:58,107 basehttp 13000 17488 "GET /sem_1_app_2/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-29 19:46:58,256 basehttp 13000 17488 "GET /sem_1_app_2/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-29 19:46:58,419 basehttp 13000 17488 "GET /sem_1_app_2/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-29 19:46:58,611 basehttp 13000 17488 "GET /sem_1_app_2/rand_num/ HTTP/1.1" 200 2
INFO 2023-08-29 19:46:58,718 basehttp 13000 17488 "GET /sem_1_app_2/rand_num/ HTTP/1.1" 200 1
INFO 2023-09-01 16:48:28,409 autoreload 17036 11116 Watching for file changes with StatReloader
INFO 2023-09-01 16:48:30,391 basehttp 17036 8876 "GET / HTTP/1.1" 200 13
WARNING 2023-09-01 16:48:30,545 log 17036 8876 Not Found: /favicon.ico
WARNING 2023-09-01 16:48:30,545 basehttp 17036 8876 "GET /favicon.ico HTTP/1.1" 404 2498
WARNING 2023-09-01 16:48:33,542 log 17036 8876 Not Found: /docs
WARNING 2023-09-01 16:48:33,542 basehttp 17036 8876 "GET /docs HTTP/1.1" 404 2477
WARNING 2023-09-01 16:48:34,768 log 17036 8876 Not Found: /dem_2
WARNING 2023-09-01 16:48:34,769 basehttp 17036 8876 "GET /dem_2 HTTP/1.1" 404 2480
INFO 2023-09-01 16:48:40,639 basehttp 17036 8876 "GET /sem_2 HTTP/1.1" 301 0
INFO 2023-09-01 16:48:40,647 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:48,706 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 79
INFO 2023-09-01 16:48:49,220 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 79
INFO 2023-09-01 16:48:49,598 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:49,811 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 79
INFO 2023-09-01 16:48:49,990 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:50,147 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:50,310 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 79
INFO 2023-09-01 16:48:50,478 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 79
INFO 2023-09-01 16:48:50,653 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:50,820 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:50,987 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:51,145 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:51,292 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 79
INFO 2023-09-01 16:48:51,452 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
INFO 2023-09-01 16:48:51,610 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 79
INFO 2023-09-01 16:48:51,777 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 79
INFO 2023-09-01 16:48:51,952 basehttp 17036 10616 "GET /sem_2/ HTTP/1.1" 200 80
WARNING 2023-09-01 16:48:56,803 log 17036 10616 Not Found: /sem_2/re
WARNING 2023-09-01 16:48:56,803 basehttp 17036 10616 "GET /sem_2/re HTTP/1.1" 404 2727
ERROR 2023-09-01 16:49:02,929 log 17036 10616 Internal Server Error: /sem_2/last/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py", line 18, in last_games
    last = GameModel().return_last(5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py", line 16, in return_last
    return self.objects.all()[:n]
           ^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\db\models\manager.py", line 186, in __get__
    raise AttributeError(
AttributeError: Manager isn't accessible via GameModel instances
ERROR 2023-09-01 16:49:02,931 basehttp 17036 10616 "GET /sem_2/last/ HTTP/1.1" 500 72241
INFO 2023-09-01 16:50:30,264 autoreload 17036 11116 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py changed, reloading.
INFO 2023-09-01 16:50:30,761 autoreload 19468 16036 Watching for file changes with StatReloader
INFO 2023-09-01 16:50:39,215 autoreload 19468 16036 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py changed, reloading.
INFO 2023-09-01 16:50:39,684 autoreload 17120 1676 Watching for file changes with StatReloader
INFO 2023-09-01 16:51:05,826 basehttp 17120 12744 "GET /sem_2/last/ HTTP/1.1" 200 398
INFO 2023-09-01 16:51:13,297 basehttp 17120 12744 "GET /sem_2/last/ HTTP/1.1" 200 398
INFO 2023-09-01 16:51:16,212 basehttp 17120 12744 "GET /sem_2/last/ HTTP/1.1" 200 398
INFO 2023-09-01 16:51:36,138 autoreload 17120 1676 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py changed, reloading.
INFO 2023-09-01 16:51:36,608 autoreload 19388 13340 Watching for file changes with StatReloader
INFO 2023-09-01 16:52:03,376 autoreload 19388 13340 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py changed, reloading.
INFO 2023-09-01 16:52:03,883 autoreload 6444 5720 Watching for file changes with StatReloader
INFO 2023-09-01 16:53:10,404 autoreload 6444 5720 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py changed, reloading.
INFO 2023-09-01 16:53:10,872 autoreload 5160 5892 Watching for file changes with StatReloader
INFO 2023-09-01 16:53:45,829 autoreload 5160 5892 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py changed, reloading.
INFO 2023-09-01 16:53:46,310 autoreload 3284 15600 Watching for file changes with StatReloader
INFO 2023-09-01 16:54:59,990 autoreload 3284 15600 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py changed, reloading.
INFO 2023-09-01 16:55:00,465 autoreload 7408 15092 Watching for file changes with StatReloader
INFO 2023-09-01 16:55:29,094 autoreload 7408 15092 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py changed, reloading.
INFO 2023-09-01 16:55:29,582 autoreload 10616 9868 Watching for file changes with StatReloader
INFO 2023-09-01 16:55:34,578 basehttp 10616 5036 "GET /sem_2/last/ HTTP/1.1" 200 418
INFO 2023-09-01 16:56:46,479 autoreload 10616 9868 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py changed, reloading.
INFO 2023-09-01 16:56:46,968 autoreload 16492 10664 Watching for file changes with StatReloader
ERROR 2023-09-01 16:56:53,114 log 16492 18828 Internal Server Error: /sem_2/last/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py", line 18, in last_games
    last = GameModel().return_last(5)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py", line 17, in return_last
    return GameModel.objects.all()[:-n]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\db\models\query.py", line 429, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2023-09-01 16:56:53,117 basehttp 16492 18828 "GET /sem_2/last/ HTTP/1.1" 500 74081
INFO 2023-09-01 16:56:57,553 autoreload 16492 10664 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py changed, reloading.
INFO 2023-09-01 16:56:58,062 autoreload 15448 7332 Watching for file changes with StatReloader
INFO 2023-09-01 16:57:25,885 autoreload 15448 7332 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py changed, reloading.
INFO 2023-09-01 16:57:26,342 autoreload 5940 2172 Watching for file changes with StatReloader
INFO 2023-09-01 16:57:33,198 basehttp 5940 15356 "GET /sem_2/last/ HTTP/1.1" 200 417
INFO 2023-09-01 16:57:33,926 basehttp 5940 15356 "GET /sem_2/last/ HTTP/1.1" 200 417
INFO 2023-09-01 16:57:40,011 autoreload 5940 2172 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py changed, reloading.
INFO 2023-09-01 16:57:40,445 autoreload 18324 8620 Watching for file changes with StatReloader
INFO 2023-09-01 16:57:42,525 basehttp 18324 13000 "GET /sem_2/last/ HTTP/1.1" 200 418
INFO 2023-09-01 16:57:55,102 autoreload 18324 8620 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\models.py changed, reloading.
INFO 2023-09-01 16:57:55,535 autoreload 15036 17916 Watching for file changes with StatReloader
INFO 2023-09-01 16:57:57,276 basehttp 15036 13008 "GET /sem_2/last/ HTTP/1.1" 200 417
INFO 2023-09-01 17:33:50,424 autoreload 3792 18248 Watching for file changes with StatReloader
INFO 2023-09-01 17:33:52,057 basehttp 3792 6044 "GET / HTTP/1.1" 200 13
WARNING 2023-09-01 17:33:54,797 log 3792 6044 Not Found: /h
WARNING 2023-09-01 17:33:54,798 basehttp 3792 6044 "GET /h HTTP/1.1" 404 2468
INFO 2023-09-01 17:34:00,142 basehttp 3792 6044 "GET /sem_2/ HTTP/1.1" 200 80
WARNING 2023-09-01 17:34:02,820 log 3792 6044 Not Found: /sem_2/g
WARNING 2023-09-01 17:34:02,820 basehttp 3792 6044 "GET /sem_2/g HTTP/1.1" 404 2901
INFO 2023-09-01 17:34:07,618 basehttp 3792 6044 "GET /sem_2/authors/ HTTP/1.1" 200 144
INFO 2023-09-01 17:34:35,714 autoreload 3792 18248 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py changed, reloading.
INFO 2023-09-01 17:34:36,187 autoreload 13000 19936 Watching for file changes with StatReloader
INFO 2023-09-01 17:34:40,683 basehttp 13000 18812 "GET /sem_2/authors/ HTTP/1.1" 200 180
INFO 2023-09-01 17:35:02,082 autoreload 13000 19936 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_2_app\views.py changed, reloading.
INFO 2023-09-01 17:35:02,583 autoreload 16168 11228 Watching for file changes with StatReloader
INFO 2023-09-01 17:35:03,790 basehttp 16168 13812 "GET /sem_2/authors/ HTTP/1.1" 200 180
INFO 2023-09-05 10:04:16,880 autoreload 5648 11628 Watching for file changes with StatReloader
INFO 2023-09-05 10:05:51,410 autoreload 7780 18968 Watching for file changes with StatReloader
INFO 2023-09-05 10:05:52,613 basehttp 7780 13816 "GET / HTTP/1.1" 200 13
INFO 2023-09-05 10:05:57,989 basehttp 7780 13816 "GET / HTTP/1.1" 200 13
WARNING 2023-09-05 10:06:00,881 log 7780 13816 Not Found: /docs
WARNING 2023-09-05 10:06:00,882 basehttp 7780 13816 "GET /docs HTTP/1.1" 404 2583
WARNING 2023-09-05 10:06:06,897 log 7780 13816 Not Found: /sem_3/
WARNING 2023-09-05 10:06:06,898 basehttp 7780 13816 "GET /sem_3/ HTTP/1.1" 404 2827
ERROR 2023-09-05 10:06:12,676 log 7780 13816 Internal Server Error: /sem_3/home/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_3_app/main.html
ERROR 2023-09-05 10:06:12,681 basehttp 7780 13816 "GET /sem_3/home/ HTTP/1.1" 500 80818
INFO 2023-09-05 10:07:24,861 autoreload 7780 18968 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py changed, reloading.
INFO 2023-09-05 10:07:25,669 autoreload 3996 18216 Watching for file changes with StatReloader
INFO 2023-09-05 10:07:28,440 basehttp 3996 15012 "GET /sem_3/home/ HTTP/1.1" 200 341
INFO 2023-09-05 10:07:34,804 basehttp 3996 15012 "GET /sem_3/about HTTP/1.1" 301 0
INFO 2023-09-05 10:07:34,811 basehttp 3996 19544 "GET /sem_3/about/ HTTP/1.1" 200 227
INFO 2023-09-05 10:14:49,320 autoreload 4480 19176 Watching for file changes with StatReloader
INFO 2023-09-05 10:14:59,432 basehttp 4480 10976 "GET / HTTP/1.1" 200 13
WARNING 2023-09-05 10:15:03,373 log 4480 10976 Not Found: /sem_3
WARNING 2023-09-05 10:15:03,374 basehttp 4480 10976 "GET /sem_3 HTTP/1.1" 404 2586
WARNING 2023-09-05 10:15:09,726 log 4480 10976 Not Found: /sem_3/
WARNING 2023-09-05 10:15:09,727 basehttp 4480 10976 "GET /sem_3/ HTTP/1.1" 404 2827
INFO 2023-09-05 10:15:14,372 basehttp 4480 10976 "GET /sem_3/about/ HTTP/1.1" 200 0
INFO 2023-09-05 10:15:33,813 basehttp 4480 10976 "GET /sem_3/about/ HTTP/1.1" 200 0
ERROR 2023-09-05 10:15:34,499 log 4480 10976 Internal Server Error: /sem_3/about/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-09-05 10:15:34,504 basehttp 4480 10976 "GET /sem_3/about/ HTTP/1.1" 500 127690
ERROR 2023-09-05 10:16:16,439 log 4480 10976 Internal Server Error: /sem_3/about/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-09-05 10:16:16,441 basehttp 4480 10976 "GET /sem_3/about/ HTTP/1.1" 500 127690
ERROR 2023-09-05 10:16:17,234 log 4480 10976 Internal Server Error: /sem_3/about/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-09-05 10:16:17,239 basehttp 4480 10976 "GET /sem_3/about/ HTTP/1.1" 500 127690
ERROR 2023-09-05 10:16:33,219 log 4480 10976 Internal Server Error: /sem_3/about/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-09-05 10:16:33,224 basehttp 4480 10976 "GET /sem_3/about/ HTTP/1.1" 500 127690
INFO 2023-09-05 10:16:38,355 autoreload 18356 9384 Watching for file changes with StatReloader
INFO 2023-09-05 10:16:41,174 basehttp 18356 19488 "GET /sem_3/about/ HTTP/1.1" 200 229
INFO 2023-09-05 10:16:47,903 basehttp 18356 19488 "GET /sem_3/about/ HTTP/1.1" 200 229
INFO 2023-09-05 10:16:50,254 basehttp 18356 19488 "GET /sem_3/about/ HTTP/1.1" 200 133
INFO 2023-09-05 10:17:05,553 basehttp 18356 19488 "GET /sem_3/about/ HTTP/1.1" 200 177
INFO 2023-09-05 10:17:09,989 basehttp 18356 19488 "GET /sem_3/about/ HTTP/1.1" 200 177
INFO 2023-09-05 10:17:10,522 basehttp 18356 19488 "GET /sem_3/about/ HTTP/1.1" 200 229
WARNING 2023-09-05 10:17:14,848 log 18356 19488 Not Found: /sem_3/main
WARNING 2023-09-05 10:17:14,849 basehttp 18356 19488 "GET /sem_3/main HTTP/1.1" 404 2839
INFO 2023-09-05 10:17:20,362 basehttp 18356 19488 "GET /sem_3/home HTTP/1.1" 301 0
INFO 2023-09-05 10:17:20,375 basehttp 18356 19652 "GET /sem_3/home/ HTTP/1.1" 200 343
INFO 2023-09-05 10:32:07,662 autoreload 21148 9696 Watching for file changes with StatReloader
INFO 2023-09-05 10:32:08,795 basehttp 21148 21848 "GET / HTTP/1.1" 200 13
INFO 2023-09-05 10:32:13,192 basehttp 21148 21848 "GET /sem_3/about/ HTTP/1.1" 200 229
WARNING 2023-09-05 10:32:17,510 log 21148 21848 Not Found: /sem_3/
WARNING 2023-09-05 10:32:17,511 basehttp 21148 21848 "GET /sem_3/ HTTP/1.1" 404 3398
WARNING 2023-09-05 10:32:21,320 log 21148 21848 Not Found: /sem_3/orel
WARNING 2023-09-05 10:32:21,320 basehttp 21148 21848 "GET /sem_3/orel HTTP/1.1" 404 3410
INFO 2023-09-05 10:32:24,559 basehttp 21148 21848 "GET /sem_3/orel/1 HTTP/1.1" 301 0
INFO 2023-09-05 10:32:24,568 basehttp 21148 11928 "GET /sem_3/orel/1/ HTTP/1.1" 200 229
INFO 2023-09-05 10:32:45,519 basehttp 21148 11928 "GET /sem_3/orel/1/ HTTP/1.1" 200 229
INFO 2023-09-05 10:32:48,074 basehttp 21148 11928 "GET /sem_3/orel/6 HTTP/1.1" 301 0
INFO 2023-09-05 10:32:48,084 basehttp 21148 11396 "GET /sem_3/orel/6/ HTTP/1.1" 200 229
INFO 2023-09-05 10:33:16,889 autoreload 21148 9696 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\urls.py changed, reloading.
INFO 2023-09-05 10:33:17,709 autoreload 14972 11500 Watching for file changes with StatReloader
INFO 2023-09-05 10:33:18,393 basehttp 14972 22456 "GET /sem_3/orel/6/ HTTP/1.1" 200 252
INFO 2023-09-05 10:33:21,863 basehttp 14972 22456 "GET /sem_3/orel/0 HTTP/1.1" 301 0
INFO 2023-09-05 10:33:21,871 basehttp 14972 2240 "GET /sem_3/orel/0/ HTTP/1.1" 200 142
INFO 2023-09-05 10:33:25,489 basehttp 14972 2240 "GET /sem_3/orel/1/ HTTP/1.1" 200 159
INFO 2023-09-05 10:33:28,648 basehttp 14972 2240 "GET /sem_3/orel/0/ HTTP/1.1" 200 142
INFO 2023-09-05 10:33:31,532 basehttp 14972 2240 "GET /sem_3/orel/10 HTTP/1.1" 301 0
INFO 2023-09-05 10:33:31,540 basehttp 14972 21724 "GET /sem_3/orel/10/ HTTP/1.1" 200 318
INFO 2023-09-05 10:33:40,899 basehttp 14972 21724 "GET /sem_3/cube/10/ HTTP/1.1" 200 230
INFO 2023-09-05 10:33:47,659 basehttp 14972 21724 "GET /sem_3/random/10/ HTTP/1.1" 200 258
INFO 2023-09-05 14:55:31,491 autoreload 13320 10128 Watching for file changes with StatReloader
INFO 2023-09-05 14:55:32,841 basehttp 13320 5804 "GET / HTTP/1.1" 200 13
WARNING 2023-09-05 14:55:36,025 log 13320 5804 Not Found: /docs
WARNING 2023-09-05 14:55:36,026 basehttp 13320 5804 "GET /docs HTTP/1.1" 404 2583
WARNING 2023-09-05 14:55:41,697 log 13320 5804 Not Found: /sem_3/
WARNING 2023-09-05 14:55:41,698 basehttp 13320 5804 "GET /sem_3/ HTTP/1.1" 404 3786
WARNING 2023-09-05 14:55:41,948 log 13320 5804 Not Found: /sem_3/
WARNING 2023-09-05 14:55:41,948 basehttp 13320 5804 "GET /sem_3/ HTTP/1.1" 404 3786
INFO 2023-09-05 14:55:50,904 basehttp 13320 5804 "GET /sem_3/post/3 HTTP/1.1" 301 0
ERROR 2023-09-05 14:55:50,969 log 13320 12156 Internal Server Error: /sem_3/post/3/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 63, in get_context_data
    author = Author.objects.get(pk=self.kwargs['id_author'])
                                   ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'id_author'
ERROR 2023-09-05 14:55:50,971 basehttp 13320 12156 "GET /sem_3/post/3/ HTTP/1.1" 500 80669
INFO 2023-09-05 14:56:30,320 autoreload 13320 10128 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\urls.py changed, reloading.
INFO 2023-09-05 14:56:30,836 autoreload 1480 18948 Watching for file changes with StatReloader
ERROR 2023-09-05 14:56:31,152 log 1480 18628 Internal Server Error: /sem_3/post/3/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_3_app/post.html
ERROR 2023-09-05 14:56:31,154 basehttp 1480 18628 "GET /sem_3/post/3/ HTTP/1.1" 500 81484
WARNING 2023-09-05 14:56:38,981 log 1480 18628 Not Found: /sem_3/author
WARNING 2023-09-05 14:56:38,981 basehttp 1480 18628 "GET /sem_3/author HTTP/1.1" 404 3804
INFO 2023-09-05 14:56:41,909 basehttp 1480 18628 "GET /sem_3/author/1 HTTP/1.1" 301 0
ERROR 2023-09-05 14:56:42,002 log 1480 4820 Internal Server Error: /sem_3/author/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' 'post' id.post">{{ post.title' from 'url 'post' id.post">{{ post.title'
ERROR 2023-09-05 14:56:42,007 basehttp 1480 4820 "GET /sem_3/author/1/ HTTP/1.1" 500 204131
ERROR 2023-09-05 14:57:01,063 log 1480 4820 Internal Server Error: /sem_3/author/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' 'post' post.id' from 'url 'post' post.id'
ERROR 2023-09-05 14:57:01,067 basehttp 1480 4820 "GET /sem_3/author/1/ HTTP/1.1" 500 205567
INFO 2023-09-05 14:57:31,903 basehttp 1480 4820 "GET /sem_3/author/1/ HTTP/1.1" 200 2539
INFO 2023-09-05 14:59:16,749 basehttp 1480 4820 "GET /sem_3/author/1/ HTTP/1.1" 200 2754
INFO 2023-09-05 14:59:32,238 basehttp 1480 4820 "GET /sem_3/author/1/ HTTP/1.1" 200 2989
INFO 2023-09-05 15:00:13,200 basehttp 1480 4820 "GET /sem_3/author/1/ HTTP/1.1" 200 2989
INFO 2023-09-05 15:00:13,749 basehttp 1480 4820 "GET /sem_3/author/1/ HTTP/1.1" 200 2989
INFO 2023-09-05 15:00:14,362 basehttp 1480 4820 "GET /sem_3/author/1/ HTTP/1.1" 200 4519
ERROR 2023-09-05 15:00:54,643 log 1480 4820 Internal Server Error: /sem_3/post/2/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: seminar_3_app/post.html
ERROR 2023-09-05 15:00:54,645 basehttp 1480 4820 "GET /sem_3/post/2/ HTTP/1.1" 500 81513
INFO 2023-09-05 15:02:11,256 basehttp 1480 4820 "GET /sem_3/post/2/ HTTP/1.1" 200 143
INFO 2023-09-05 15:02:12,833 basehttp 1480 4820 "GET /sem_3/post/2/ HTTP/1.1" 200 143
INFO 2023-09-05 15:02:40,330 basehttp 1480 4820 "GET /sem_3/post/2/ HTTP/1.1" 200 143
INFO 2023-09-05 15:02:43,403 basehttp 1480 4820 "GET /sem_3/post/5 HTTP/1.1" 301 0
INFO 2023-09-05 15:02:43,409 basehttp 1480 19000 "GET /sem_3/post/5/ HTTP/1.1" 200 143
INFO 2023-09-05 15:02:55,336 basehttp 1480 19000 "GET /sem_3/post/5/ HTTP/1.1" 200 143
INFO 2023-09-05 15:02:55,951 basehttp 1480 19000 "GET /sem_3/post/5/ HTTP/1.1" 200 144
INFO 2023-09-05 15:02:56,240 basehttp 1480 19000 "GET /sem_3/post/5/ HTTP/1.1" 200 144
INFO 2023-09-05 15:03:29,727 basehttp 1480 19000 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:03:30,392 basehttp 1480 19000 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:03:30,986 basehttp 1480 19000 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:03:31,214 basehttp 1480 19000 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:16,189 autoreload 1480 18948 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py changed, reloading.
INFO 2023-09-05 15:04:16,643 autoreload 10204 21924 Watching for file changes with StatReloader
INFO 2023-09-05 15:04:17,669 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:18,270 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:18,924 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:19,378 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:19,542 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:19,706 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:19,884 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:20,070 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:20,217 basehttp 10204 18896 "GET /sem_3/post/5/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:24,094 autoreload 19756 20064 Watching for file changes with StatReloader
INFO 2023-09-05 15:04:27,627 basehttp 19756 21384 "GET /sem_3/post/6 HTTP/1.1" 301 0
INFO 2023-09-05 15:04:27,636 basehttp 19756 1788 "GET /sem_3/post/6/ HTTP/1.1" 200 145
INFO 2023-09-05 15:04:33,730 autoreload 19756 20064 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py changed, reloading.
INFO 2023-09-05 15:04:34,196 autoreload 2960 2488 Watching for file changes with StatReloader
ERROR 2023-09-05 15:04:35,482 log 2960 14092 Internal Server Error: /sem_3/post/6/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 74, in get_context_data
    post = Post.objects.get(pk=self.kwargs['id_post']).all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'all'
ERROR 2023-09-05 15:04:35,484 basehttp 2960 14092 "GET /sem_3/post/6/ HTTP/1.1" 500 80339
ERROR 2023-09-05 15:04:48,848 log 2960 14092 Internal Server Error: /sem_3/post/6/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 74, in get_context_data
    post = Post.objects.get(pk=self.kwargs['id_post'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'all'
ERROR 2023-09-05 15:04:48,849 basehttp 2960 14092 "GET /sem_3/post/6/ HTTP/1.1" 500 80327
INFO 2023-09-05 15:04:48,971 autoreload 2960 2488 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py changed, reloading.
INFO 2023-09-05 15:04:49,522 autoreload 22308 7368 Watching for file changes with StatReloader
INFO 2023-09-05 15:04:49,662 basehttp 22308 5456 "GET /sem_3/post/6/ HTTP/1.1" 200 156
INFO 2023-09-05 15:04:56,190 basehttp 22308 5456 "GET /sem_3/post/6/ HTTP/1.1" 200 156
INFO 2023-09-05 15:04:59,989 basehttp 22308 5456 "GET /sem_3/post/5/ HTTP/1.1" 200 156
INFO 2023-09-05 15:05:12,435 basehttp 22308 5456 "GET /sem_3/post/5/ HTTP/1.1" 200 182
INFO 2023-09-05 15:05:18,958 basehttp 22308 5456 "GET /sem_3/post/5/ HTTP/1.1" 200 178
INFO 2023-09-05 15:05:19,498 basehttp 22308 5456 "GET /sem_3/post/5/ HTTP/1.1" 200 178
INFO 2023-09-05 15:05:25,194 basehttp 22308 5456 "GET /sem_3/author/1/ HTTP/1.1" 200 4519
INFO 2023-09-05 15:05:27,655 basehttp 22308 5456 "GET /sem_3/post/901/ HTTP/1.1" 200 178
INFO 2023-09-05 15:05:30,656 basehttp 22308 5456 "GET /sem_3/post/1084/ HTTP/1.1" 200 178
INFO 2023-09-05 15:05:35,101 basehttp 22308 5456 "GET /sem_3/post/273/ HTTP/1.1" 200 178
INFO 2023-09-05 15:05:37,478 basehttp 22308 5456 "GET /sem_3/post/92/ HTTP/1.1" 200 178
INFO 2023-09-05 15:29:21,092 autoreload 1436 16296 Watching for file changes with StatReloader
INFO 2023-09-05 15:29:22,256 basehttp 1436 6952 "GET / HTTP/1.1" 200 13
WARNING 2023-09-05 15:29:27,163 log 1436 6952 Not Found: /sem_3/
WARNING 2023-09-05 15:29:27,164 basehttp 1436 6952 "GET /sem_3/ HTTP/1.1" 404 3786
ERROR 2023-09-05 15:29:30,284 log 1436 6952 Internal Server Error: /sem_3/author/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 914, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py", line 33, in get_absolute_url
    return reverse('post', kwargs={'pk': self.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post' with keyword arguments '{'pk': 2}' not found. 1 pattern(s) tried: ['sem_3/post/(?P<id_post>[0-9]+)/\\Z']
ERROR 2023-09-05 15:29:30,291 basehttp 1436 6952 "GET /sem_3/author/1/ HTTP/1.1" 500 231277
INFO 2023-09-05 15:29:58,312 autoreload 1436 16296 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-05 15:29:58,778 autoreload 20532 19820 Watching for file changes with StatReloader
INFO 2023-09-05 15:30:00,070 basehttp 20532 22404 "GET /sem_3/author/1/ HTTP/1.1" 200 7094
ERROR 2023-09-05 15:30:01,294 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:30:01,296 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85548
ERROR 2023-09-05 15:31:35,869 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:35,871 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:36,482 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:36,484 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:37,076 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:37,077 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:37,233 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:37,234 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:37,384 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:37,385 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:37,528 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:37,530 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:38,000 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:38,002 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:38,157 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:38,158 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:38,322 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:38,323 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:38,512 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:38,513 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:38,680 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:38,681 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:38,871 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:38,873 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:39,074 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:39,076 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:39,443 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:39,445 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:39,601 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:39,603 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
ERROR 2023-09-05 15:31:39,759 log 20532 22404 Internal Server Error: /sem_3/post/92/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py", line 75, in get_object
    obj = super().get_object(queryset=queryset)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view PostViews must be called with either an object pk or a slug in the URLconf.
ERROR 2023-09-05 15:31:39,760 basehttp 20532 22404 "GET /sem_3/post/92/ HTTP/1.1" 500 85685
INFO 2023-09-05 15:32:12,298 autoreload 20532 19820 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\urls.py changed, reloading.
INFO 2023-09-05 15:32:12,773 autoreload 9036 2352 Watching for file changes with StatReloader
INFO 2023-09-05 15:32:15,234 basehttp 9036 12232 "GET /sem_3/post/92/ HTTP/1.1" 200 176
INFO 2023-09-05 15:32:22,968 basehttp 9036 12232 "GET /sem_3/post/1 HTTP/1.1" 301 0
INFO 2023-09-05 15:32:22,979 basehttp 9036 21496 "GET /sem_3/post/1/ HTTP/1.1" 200 176
INFO 2023-09-05 15:32:36,606 basehttp 9036 21496 "GET /sem_3/post/1/ HTTP/1.1" 200 176
INFO 2023-09-05 15:32:37,004 basehttp 9036 21496 "GET /sem_3/post/1/ HTTP/1.1" 200 176
INFO 2023-09-05 15:32:37,458 basehttp 9036 21496 "GET /sem_3/post/1/ HTTP/1.1" 200 176
INFO 2023-09-05 15:32:37,936 basehttp 9036 21496 "GET /sem_3/post/1/ HTTP/1.1" 200 176
INFO 2023-09-05 15:32:38,696 basehttp 9036 21496 "GET /sem_3/post/1/ HTTP/1.1" 200 176
INFO 2023-09-05 15:50:58,625 autoreload 20564 2284 Watching for file changes with StatReloader
INFO 2023-09-05 15:51:00,118 basehttp 20564 20944 "GET / HTTP/1.1" 200 13
INFO 2023-09-05 15:51:04,695 basehttp 20564 20944 "GET /sem_3/post/5/ HTTP/1.1" 200 244
INFO 2023-09-05 15:51:10,526 basehttp 20564 20944 "GET /sem_3/post/1/ HTTP/1.1" 200 244
INFO 2023-09-05 15:51:21,684 basehttp 20564 20944 "GET /sem_3/post/1/ HTTP/1.1" 200 244
INFO 2023-09-05 15:51:41,059 basehttp 20564 20944 "GET /sem_3/post/1/ HTTP/1.1" 200 244
INFO 2023-09-05 15:56:38,379 autoreload 20824 6348 Watching for file changes with StatReloader
ERROR 2023-09-05 15:56:40,168 log 20824 17756 Internal Server Error: /sem_3/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'author' with arguments '('',)' not found. 1 pattern(s) tried: ['sem_3/author/(?P<id_author>[0-9]+)/\\Z']
ERROR 2023-09-05 15:56:40,172 basehttp 20824 17756 "GET /sem_3/post/1/ HTTP/1.1" 500 190128
INFO 2023-09-05 15:57:22,541 basehttp 20824 17756 "GET /sem_3/post/1/ HTTP/1.1" 200 2481
ERROR 2023-09-05 15:58:44,035 log 20824 17756 Internal Server Error: /sem_3/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 18: 'endfor', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
ERROR 2023-09-05 15:58:44,040 basehttp 20824 17756 "GET /sem_3/post/1/ HTTP/1.1" 500 200320
ERROR 2023-09-05 15:58:45,181 log 20824 17756 Internal Server Error: /sem_3/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 18: 'endfor', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
ERROR 2023-09-05 15:58:45,185 basehttp 20824 17756 "GET /sem_3/post/1/ HTTP/1.1" 500 200320
INFO 2023-09-05 15:58:57,802 basehttp 20824 17756 "GET /sem_3/post/1/ HTTP/1.1" 200 2985
INFO 2023-09-05 15:59:39,246 basehttp 20824 17756 "GET /sem_3/post/1/ HTTP/1.1" 200 2916
ERROR 2023-09-05 16:00:50,406 log 20824 17756 Internal Server Error: /sem_3/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'author' with arguments '(<Author: Name9 Last Name9>,)' not found. 1 pattern(s) tried: ['sem_3/author/(?P<id_author>[0-9]+)/\\Z']
ERROR 2023-09-05 16:00:50,408 basehttp 20824 17756 "GET /sem_3/post/1/ HTTP/1.1" 500 190954
INFO 2023-09-05 16:01:02,934 basehttp 20824 17756 "GET /sem_3/post/1/ HTTP/1.1" 200 3070
INFO 2023-09-05 16:01:04,272 basehttp 20824 17756 "GET /sem_3/author/9/ HTTP/1.1" 200 7096
INFO 2023-09-05 16:02:40,506 autoreload 20824 6348 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py changed, reloading.
INFO 2023-09-05 16:02:40,962 autoreload 14716 20136 Watching for file changes with StatReloader
INFO 2023-09-05 16:02:43,266 basehttp 14716 9928 "GET /sem_3/post/1/ HTTP/1.1" 200 3070
WARNING 2023-09-05 16:03:04,917 log 14716 9928 Not Found: /sem_3/
WARNING 2023-09-05 16:03:04,917 basehttp 14716 9928 "GET /sem_3/ HTTP/1.1" 404 3781
WARNING 2023-09-05 16:03:05,454 log 14716 9928 Not Found: /sem_3/
WARNING 2023-09-05 16:03:05,454 basehttp 14716 9928 "GET /sem_3/ HTTP/1.1" 404 3781
INFO 2023-09-05 16:03:29,968 autoreload 19288 4820 Watching for file changes with StatReloader
INFO 2023-09-05 16:03:31,412 basehttp 19288 19880 "GET / HTTP/1.1" 200 13
WARNING 2023-09-05 16:03:39,457 log 19288 19880 Not Found: /sem_3
WARNING 2023-09-05 16:03:39,458 basehttp 19288 19880 "GET /sem_3 HTTP/1.1" 404 2586
INFO 2023-09-05 16:03:46,974 basehttp 19288 19880 "GET /sem_3/author/1/ HTTP/1.1" 200 7094
INFO 2023-09-05 16:03:52,415 basehttp 19288 19880 "GET /sem_3/post/2/ HTTP/1.1" 200 270
INFO 2023-09-05 16:03:55,259 basehttp 19288 19880 "GET /sem_3/post/92/ HTTP/1.1" 200 270
INFO 2023-09-05 16:03:56,995 basehttp 19288 19880 "GET /sem_3/post/271/ HTTP/1.1" 200 270
INFO 2023-09-05 16:03:58,911 basehttp 19288 19880 "GET /sem_3/post/364/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:00,857 basehttp 19288 19880 "GET /sem_3/post/901/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:02,233 basehttp 19288 19880 "GET /sem_3/post/903/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:03,396 basehttp 19288 19880 "GET /sem_3/post/902/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:04,871 basehttp 19288 19880 "GET /sem_3/post/994/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:06,314 basehttp 19288 19880 "GET /sem_3/post/1173/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:07,370 basehttp 19288 19880 "GET /sem_3/post/1174/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:19,850 basehttp 19288 19880 "GET /sem_3/author/2 HTTP/1.1" 301 0
INFO 2023-09-05 16:04:19,888 basehttp 19288 20648 "GET /sem_3/author/2/ HTTP/1.1" 200 7985
INFO 2023-09-05 16:04:21,281 basehttp 19288 20648 "GET /sem_3/post/6/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:22,528 basehttp 19288 20648 "GET /sem_3/post/8/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:23,653 basehttp 19288 20648 "GET /sem_3/post/98/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:24,701 basehttp 19288 20648 "GET /sem_3/post/10/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:34,386 basehttp 19288 20648 "GET /sem_3/post/279/ HTTP/1.1" 200 270
INFO 2023-09-05 16:04:37,594 basehttp 19288 20648 "GET /sem_3/post/1/ HTTP/1.1" 200 3070
INFO 2023-09-05 16:04:46,121 basehttp 19288 20648 "GET /sem_3/author/6/ HTTP/1.1" 200 7100
INFO 2023-09-05 16:04:47,819 basehttp 19288 20648 "GET /sem_3/author/6/ HTTP/1.1" 200 7100
INFO 2023-09-05 16:04:49,038 basehttp 19288 20648 "GET /sem_3/author/4/ HTTP/1.1" 200 7773
INFO 2023-09-05 16:04:50,606 basehttp 19288 20648 "GET /sem_3/author/17/ HTTP/1.1" 200 7877
INFO 2023-09-09 16:37:15,449 autoreload 15588 15796 Watching for file changes with StatReloader
INFO 2023-09-09 16:37:16,821 basehttp 15588 24440 "GET / HTTP/1.1" 200 13
INFO 2023-09-09 16:37:20,476 basehttp 15588 24440 "GET /sem_3/author/1/ HTTP/1.1" 200 7094
WARNING 2023-09-09 16:37:24,036 log 15588 24440 Not Found: /sem_
WARNING 2023-09-09 16:37:24,036 basehttp 15588 24440 "GET /sem_ HTTP/1.1" 404 2689
WARNING 2023-09-09 16:37:26,800 log 15588 24440 Not Found: /sem_4
WARNING 2023-09-09 16:37:26,800 basehttp 15588 24440 "GET /sem_4 HTTP/1.1" 404 2692
WARNING 2023-09-09 16:37:29,420 log 15588 24440 Not Found: /sem_4/
WARNING 2023-09-09 16:37:29,421 basehttp 15588 24440 "GET /sem_4/ HTTP/1.1" 404 2765
INFO 2023-09-09 16:37:32,724 basehttp 15588 24440 "GET /sem_4/game HTTP/1.1" 301 0
INFO 2023-09-09 16:37:32,783 basehttp 15588 2528 "GET /sem_4/game/ HTTP/1.1" 200 803
INFO 2023-09-09 16:37:40,111 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:41,896 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:42,356 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:42,769 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:46,010 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:46,140 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:46,271 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:46,414 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:46,575 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:46,745 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:46,905 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:47,077 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1075
INFO 2023-09-09 16:37:49,075 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1035
INFO 2023-09-09 16:37:50,198 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1035
INFO 2023-09-09 16:37:50,450 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1035
INFO 2023-09-09 16:37:50,612 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1035
INFO 2023-09-09 16:37:50,760 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1035
INFO 2023-09-09 16:37:50,908 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1035
INFO 2023-09-09 16:37:51,046 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1035
INFO 2023-09-09 16:37:52,943 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1043
INFO 2023-09-09 16:37:54,176 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1043
INFO 2023-09-09 16:37:54,418 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1042
INFO 2023-09-09 16:37:54,579 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1044
INFO 2023-09-09 16:37:54,738 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1043
INFO 2023-09-09 16:37:54,878 basehttp 15588 2528 "POST /sem_4/game/ HTTP/1.1" 200 1045
INFO 2023-09-09 16:45:39,826 autoreload 15588 15796 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_4_app\views.py changed, reloading.
INFO 2023-09-09 16:45:40,249 autoreload 20484 23576 Watching for file changes with StatReloader
INFO 2023-09-09 16:45:41,437 autoreload 20484 23576 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_4_app\views.py changed, reloading.
INFO 2023-09-09 16:45:41,892 autoreload 9512 6664 Watching for file changes with StatReloader
INFO 2023-09-09 16:58:44,174 autoreload 19264 16752 Watching for file changes with StatReloader
INFO 2023-09-09 16:58:45,197 basehttp 19264 22056 "GET / HTTP/1.1" 200 13
WARNING 2023-09-09 16:58:49,784 log 19264 22056 Not Found: /sem_4
WARNING 2023-09-09 16:58:49,784 basehttp 19264 22056 "GET /sem_4 HTTP/1.1" 404 2692
WARNING 2023-09-09 16:58:52,015 log 19264 22056 Not Found: /sem_4/
WARNING 2023-09-09 16:58:52,015 basehttp 19264 22056 "GET /sem_4/ HTTP/1.1" 404 3147
INFO 2023-09-09 16:58:58,412 basehttp 19264 22056 "GET /sem_4/add_author HTTP/1.1" 301 0
INFO 2023-09-09 16:58:58,437 basehttp 19264 25232 "GET /sem_4/add_author/ HTTP/1.1" 200 1142
INFO 2023-09-09 17:00:44,089 basehttp 19264 25232 "POST /sem_4/add_author/ HTTP/1.1" 200 1275
INFO 2023-09-09 17:01:06,414 basehttp 19264 25232 "POST /sem_4/add_author/ HTTP/1.1" 200 1273
INFO 2023-09-09 17:01:13,328 basehttp 19264 25232 "POST /sem_4/add_author/ HTTP/1.1" 200 1275
INFO 2023-09-09 17:01:16,001 basehttp 19264 25232 "POST /sem_4/add_author/ HTTP/1.1" 200 1275
INFO 2023-09-09 17:01:54,178 basehttp 19264 25232 "POST /sem_4/add_author/ HTTP/1.1" 200 1275
INFO 2023-09-09 17:03:34,972 autoreload 19264 16752 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 17:03:35,440 autoreload 23536 5116 Watching for file changes with StatReloader
INFO 2023-09-09 17:03:55,428 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1275
INFO 2023-09-09 17:03:57,425 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1275
WARNING 2023-09-09 17:04:01,912 log 23536 16064 Not Found: /sem_4/add_aut
WARNING 2023-09-09 17:04:01,913 basehttp 23536 16064 "GET /sem_4/add_aut HTTP/1.1" 404 3168
INFO 2023-09-09 17:04:05,268 basehttp 23536 16064 "GET /sem_4/add_author/ HTTP/1.1" 200 1142
INFO 2023-09-09 17:04:29,003 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:38,607 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:39,212 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:39,388 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:39,557 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:39,720 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:39,878 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:40,050 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:40,269 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:04:46,135 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 200 1274
INFO 2023-09-09 17:05:43,321 basehttp 23536 16064 "GET /sem_4/author_page/4 HTTP/1.1" 200 180
WARNING 2023-09-09 17:05:47,265 log 23536 16064 Not Found: /sem_4/author_page/20
WARNING 2023-09-09 17:05:47,266 basehttp 23536 16064 "GET /sem_4/author_page/20 HTTP/1.1" 404 3357
WARNING 2023-09-09 17:05:50,256 log 23536 16064 Not Found: /sem_4/author_page/19
WARNING 2023-09-09 17:05:50,257 basehttp 23536 16064 "GET /sem_4/author_page/19 HTTP/1.1" 404 3357
INFO 2023-09-09 17:05:53,704 basehttp 23536 16064 "GET /sem_4/author_page/18 HTTP/1.1" 200 180
INFO 2023-09-09 17:05:59,079 basehttp 23536 16064 "GET /sem_4/add_author/ HTTP/1.1" 200 1142
ERROR 2023-09-09 17:06:28,061 log 23536 16064 Internal Server Error: /sem_4/add_author/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'seminar_4_app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py", line 19, in get_absolute_url
    return reverse('seminar_4_app:author_page', kwargs={'pk': self.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'seminar_4_app' is not a registered namespace
ERROR 2023-09-09 17:06:28,064 basehttp 23536 16064 "POST /sem_4/add_author/ HTTP/1.1" 500 111778
INFO 2023-09-09 17:08:59,926 autoreload 23536 5116 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 17:09:00,427 autoreload 7164 24160 Watching for file changes with StatReloader
INFO 2023-09-09 17:09:01,358 basehttp 7164 16728 "GET / HTTP/1.1" 200 13
WARNING 2023-09-09 17:09:07,628 log 7164 16728 Not Found: /sem_3/
WARNING 2023-09-09 17:09:07,628 basehttp 7164 16728 "GET /sem_3/ HTTP/1.1" 404 3887
INFO 2023-09-09 17:09:09,424 basehttp 7164 16728 "GET /sem_4/add_author/ HTTP/1.1" 200 1142
INFO 2023-09-09 17:09:19,181 basehttp 7164 16728 "POST /sem_4/add_author/ HTTP/1.1" 302 0
INFO 2023-09-09 17:09:19,186 basehttp 7164 16728 "GET /sem_4/author_page/20 HTTP/1.1" 200 176
INFO 2023-09-09 17:17:17,434 autoreload 23956 14972 Watching for file changes with StatReloader
INFO 2023-09-09 17:17:18,516 basehttp 23956 23208 "GET / HTTP/1.1" 200 13
INFO 2023-09-09 17:17:27,447 basehttp 23956 23208 "GET /sem_4/add_post HTTP/1.1" 301 0
INFO 2023-09-09 17:17:27,465 basehttp 23956 6992 "GET /sem_4/add_post/ HTTP/1.1" 200 2787
INFO 2023-09-09 17:17:47,207 basehttp 23956 6992 "POST /sem_4/add_post/ HTTP/1.1" 302 0
INFO 2023-09-09 17:17:47,240 basehttp 23956 6992 "GET /sem_3/post/1351/ HTTP/1.1" 200 365
INFO 2023-09-09 17:18:19,722 basehttp 23956 6992 "GET /sem_3/post/1351/ HTTP/1.1" 200 365
INFO 2023-09-09 17:18:56,591 basehttp 23956 6992 "GET /sem_3/post/1351/ HTTP/1.1" 200 365
INFO 2023-09-09 18:31:52,377 basehttp 23956 7732 "GET / HTTP/1.1" 200 13
INFO 2023-09-09 18:32:00,963 basehttp 23956 7732 "GET /sem_3/post/1 HTTP/1.1" 301 0
INFO 2023-09-09 18:32:00,983 basehttp 23956 23104 "GET /sem_3/post/1/ HTTP/1.1" 200 3070
INFO 2023-09-09 18:33:17,689 basehttp 23956 23104 "GET /sem_3/post/1/ HTTP/1.1" 200 3575
INFO 2023-09-09 18:33:50,885 basehttp 23956 23104 "GET /sem_3/post/1/ HTTP/1.1" 200 3571
INFO 2023-09-09 18:34:38,466 basehttp 23956 23104 "GET /sem_3/post/1/ HTTP/1.1" 200 3481
INFO 2023-09-09 18:36:28,908 basehttp 23956 23104 "GET /sem_3/post/1/ HTTP/1.1" 200 3482
INFO 2023-09-09 18:36:32,687 basehttp 23956 23104 "GET /sem_3/author/6/ HTTP/1.1" 200 7100
INFO 2023-09-09 18:36:55,255 basehttp 23956 23104 "GET /sem_3/author/6/ HTTP/1.1" 200 7100
INFO 2023-09-09 18:44:16,902 autoreload 24996 18100 Watching for file changes with StatReloader
INFO 2023-09-09 18:44:18,241 basehttp 24996 14032 "GET /sem_3/post/1/ HTTP/1.1" 200 3482
INFO 2023-09-09 18:44:19,485 basehttp 24996 14032 "GET /sem_3/post/1/ HTTP/1.1" 200 3482
INFO 2023-09-09 18:44:24,912 basehttp 24996 14032 "GET /sem_4/post/1/ HTTP/1.1" 200 2954
INFO 2023-09-09 18:44:27,188 basehttp 24996 14032 "GET /sem_4/post/1/ HTTP/1.1" 200 2954
INFO 2023-09-09 18:44:37,600 basehttp 24996 14032 "GET /sem_4/post/2/ HTTP/1.1" 200 243
INFO 2023-09-09 18:44:40,896 basehttp 24996 14032 "GET /sem_4/post/1/ HTTP/1.1" 200 2954
INFO 2023-09-09 18:45:08,801 basehttp 24996 14032 "GET /sem_3/author/6/ HTTP/1.1" 200 7100
INFO 2023-09-09 18:45:09,622 basehttp 24996 14032 "GET /sem_4/post/118/ HTTP/1.1" 200 243
INFO 2023-09-09 18:45:11,977 basehttp 24996 14032 "GET /sem_3/author/6/ HTTP/1.1" 200 7100
INFO 2023-09-09 18:46:14,720 basehttp 24996 14032 "GET /sem_3/post/1/ HTTP/1.1" 200 3482
INFO 2023-09-09 18:46:17,799 basehttp 24996 14032 "GET /sem_4/post/1/ HTTP/1.1" 200 2954
INFO 2023-09-09 18:47:00,802 basehttp 24996 14032 "GET /sem_4/post/1/ HTTP/1.1" 200 2954
INFO 2023-09-09 18:47:00,844 autoreload 24996 18100 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\views.py changed, reloading.
INFO 2023-09-09 18:47:01,339 autoreload 17752 18772 Watching for file changes with StatReloader
INFO 2023-09-09 18:47:04,057 basehttp 17752 22644 "GET /sem_4/post/1/ HTTP/1.1" 200 2954
INFO 2023-09-09 18:47:04,569 basehttp 17752 22644 "GET /sem_4/post/1/ HTTP/1.1" 200 2954
INFO 2023-09-09 18:48:04,328 basehttp 17752 22644 "GET /sem_4/post/1/ HTTP/1.1" 200 81485
ERROR 2023-09-09 18:48:24,407 log 17752 22644 Internal Server Error: /sem_4/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Comment' object has no attribute 'get_absolute_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 127, in get_success_url
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model.
ERROR 2023-09-09 18:48:24,409 basehttp 17752 22644 "POST /sem_4/post/1/ HTTP/1.1" 500 99490
INFO 2023-09-09 18:49:22,947 autoreload 17752 18772 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 18:49:23,473 autoreload 5660 17776 Watching for file changes with StatReloader
ERROR 2023-09-09 18:49:26,861 log 5660 24368 Internal Server Error: /sem_4/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Comment' object has no attribute 'get_absolute_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 127, in get_success_url
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model.
ERROR 2023-09-09 18:49:26,862 basehttp 5660 24368 "POST /sem_4/post/1/ HTTP/1.1" 500 99490
INFO 2023-09-09 18:49:46,452 autoreload 5660 17776 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 18:49:46,955 autoreload 5476 19016 Watching for file changes with StatReloader
INFO 2023-09-09 18:50:09,713 autoreload 5476 19016 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 18:50:10,179 autoreload 22816 21476 Watching for file changes with StatReloader
INFO 2023-09-09 18:50:10,489 basehttp 22816 21864 "POST /sem_4/post/1/ HTTP/1.1" 302 0
INFO 2023-09-09 18:50:10,959 basehttp 22816 21864 "GET /sem_4/post/123/ HTTP/1.1" 200 78774
INFO 2023-09-09 18:50:15,372 basehttp 22816 21864 "GET /sem_4/post/123/ HTTP/1.1" 200 78774
INFO 2023-09-09 18:50:16,304 basehttp 22816 21864 "GET /sem_4/post/1/ HTTP/1.1" 200 82257
INFO 2023-09-09 18:50:18,216 basehttp 22816 21864 "GET /sem_4/post/1/ HTTP/1.1" 200 82257
INFO 2023-09-09 18:50:25,251 basehttp 22816 21864 "POST /sem_4/post/1/ HTTP/1.1" 302 0
INFO 2023-09-09 18:50:25,732 basehttp 22816 21864 "GET /sem_4/post/124/ HTTP/1.1" 200 78774
INFO 2023-09-09 18:50:46,807 basehttp 22816 21864 - Broken pipe from ('127.0.0.1', 56086)
INFO 2023-09-09 18:50:47,271 basehttp 22816 15700 "GET /sem_4/post/1/ HTTP/1.1" 200 82500
INFO 2023-09-09 18:51:37,769 autoreload 9180 23648 Watching for file changes with StatReloader
INFO 2023-09-09 18:51:38,612 basehttp 9180 13720 "GET / HTTP/1.1" 200 13
INFO 2023-09-09 18:51:46,712 basehttp 9180 13720 "GET /sem_4/post/1/ HTTP/1.1" 200 82499
INFO 2023-09-09 18:53:37,084 autoreload 9180 23648 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_4_app\views.py changed, reloading.
INFO 2023-09-09 18:53:37,523 autoreload 22684 23928 Watching for file changes with StatReloader
INFO 2023-09-09 18:53:38,976 basehttp 22684 19136 "GET /sem_4/post/1/ HTTP/1.1" 200 83027
INFO 2023-09-09 18:53:52,181 basehttp 22684 19136 "POST /sem_4/post/1/ HTTP/1.1" 302 0
INFO 2023-09-09 18:53:52,662 basehttp 22684 19136 "GET /sem_4/post/125/ HTTP/1.1" 200 78790
INFO 2023-09-09 18:54:51,698 autoreload 22684 23928 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 18:54:52,201 autoreload 17828 2512 Watching for file changes with StatReloader
ERROR 2023-09-09 18:54:52,800 log 17828 24628 Internal Server Error: /sem_4/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py", line 53, in get_absolute_url
    return reverse('post', kwargs={'pk': Post.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post' with keyword arguments '{'pk': <property object at 0x0000023838854B80>}' not found. 2 pattern(s) tried: ['sem_4/post/(?P<pk>[0-9]+)/\\Z', 'sem_3/post/(?P<pk>[0-9]+)/\\Z']
ERROR 2023-09-09 18:54:52,803 basehttp 17828 24628 "POST /sem_4/post/1/ HTTP/1.1" 500 113072
INFO 2023-09-09 18:57:23,701 autoreload 17828 2512 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 18:57:24,122 autoreload 25340 4304 Watching for file changes with StatReloader
INFO 2023-09-09 18:59:13,661 autoreload 19732 10772 Watching for file changes with StatReloader
INFO 2023-09-09 18:59:13,809 basehttp 19732 20212 "GET / HTTP/1.1" 200 13
INFO 2023-09-09 18:59:24,702 basehttp 19732 20212 "GET /sem_4/post/1/ HTTP/1.1" 200 83542
ERROR 2023-09-09 18:59:39,519 log 19732 20212 Internal Server Error: /sem_4/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Comment' object has no attribute 'get_absolute_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 127, in get_success_url
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model.
ERROR 2023-09-09 18:59:39,521 basehttp 19732 20212 "POST /sem_4/post/1/ HTTP/1.1" 500 99470
INFO 2023-09-09 19:00:04,942 basehttp 19732 20212 "GET /sem_4/post/1/ HTTP/1.1" 200 83780
INFO 2023-09-09 19:00:31,952 basehttp 19732 20212 "GET /sem_4/post/1/ HTTP/1.1" 200 83780
INFO 2023-09-09 19:00:33,647 basehttp 19732 20212 "GET /sem_4/post/1/ HTTP/1.1" 200 84360
INFO 2023-09-09 19:00:36,578 basehttp 19732 20212 "GET /sem_4/post/1/ HTTP/1.1" 200 84360
INFO 2023-09-09 19:00:56,117 basehttp 19732 20212 "GET /sem_4/post/1/ HTTP/1.1" 200 84360
INFO 2023-09-09 19:00:57,404 basehttp 19732 20212 "GET /sem_4/post/1/ HTTP/1.1" 200 83751
INFO 2023-09-09 19:01:39,103 autoreload 19732 10772 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 19:01:39,606 autoreload 19176 21356 Watching for file changes with StatReloader
ERROR 2023-09-09 19:01:44,367 log 19176 23952 Internal Server Error: /sem_4/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py", line 53, in get_absolute_url
    return reverse('post', kwargs={'pk': Post.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post' with keyword arguments '{'pk': <property object at 0x000002D1D2424B30>}' not found. 2 pattern(s) tried: ['sem_4/post/(?P<pk>[0-9]+)/\\Z', 'sem_3/post/(?P<pk>[0-9]+)/\\Z']
ERROR 2023-09-09 19:01:44,370 basehttp 19176 23952 "POST /sem_4/post/1/ HTTP/1.1" 500 113062
ERROR 2023-09-09 19:04:09,502 log 19176 23952 Internal Server Error: /sem_4/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py", line 53, in get_absolute_url
    return reverse('post', kwargs={'pk': Post.pk})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post' with keyword arguments '{'pk': <property object at 0x000002D1D2424B30>}' not found. 2 pattern(s) tried: ['sem_4/post/(?P<pk>[0-9]+)/\\Z', 'sem_3/post/(?P<pk>[0-9]+)/\\Z']
ERROR 2023-09-09 19:04:09,504 basehttp 19176 23952 "POST /sem_4/post/1/ HTTP/1.1" 500 113062
INFO 2023-09-09 19:04:11,608 basehttp 19176 23952 "GET /sem_4/post/1/ HTTP/1.1" 200 84225
INFO 2023-09-09 19:04:22,940 autoreload 19176 21356 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 19:04:23,402 autoreload 20936 2216 Watching for file changes with StatReloader
ERROR 2023-09-09 19:04:26,003 log 20936 11492 Internal Server Error: /sem_4/post/1/
Traceback (most recent call last):
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 136, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 65, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\venv\Lib\site-packages\django\views\generic\edit.py", line 125, in get_success_url
    url = self.object.get_absolute_url()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py", line 53, in get_absolute_url
    return reverse('post', kwargs={'pk': post.pk})
                                         ^^^^
NameError: name 'post' is not defined
ERROR 2023-09-09 19:04:26,006 basehttp 20936 11492 "POST /sem_4/post/1/ HTTP/1.1" 500 98435
INFO 2023-09-09 19:04:47,321 autoreload 20936 2216 C:\Users\gapli\Downloads\GB_Django\Seminars\seminar_project\seminar_3_app\models.py changed, reloading.
INFO 2023-09-09 19:04:47,799 autoreload 22664 22932 Watching for file changes with StatReloader
INFO 2023-09-09 19:04:48,586 basehttp 22664 13692 "POST /sem_4/post/1/ HTTP/1.1" 302 0
INFO 2023-09-09 19:04:49,052 basehttp 22664 13692 "GET /sem_4/post/11/ HTTP/1.1" 200 79501
INFO 2023-09-09 19:05:06,196 basehttp 22664 13692 - Broken pipe from ('127.0.0.1', 56479)
INFO 2023-09-09 19:05:06,652 basehttp 22664 24816 "GET /sem_4/post/1/ HTTP/1.1" 200 84223
INFO 2023-09-09 19:05:13,644 basehttp 22664 24816 "POST /sem_4/post/1/ HTTP/1.1" 302 0
INFO 2023-09-09 19:05:14,141 basehttp 22664 24816 "GET /sem_4/post/1/ HTTP/1.1" 200 84458
INFO 2023-09-09 19:06:34,326 autoreload 4568 18300 Watching for file changes with StatReloader
INFO 2023-09-09 19:06:36,070 basehttp 4568 3928 "GET / HTTP/1.1" 200 13
INFO 2023-09-09 19:06:42,628 basehttp 4568 3928 "GET /sem_4/post/1/ HTTP/1.1" 200 84458
INFO 2023-09-09 19:06:43,935 basehttp 4568 3928 "GET /sem_4/post/1 HTTP/1.1" 301 0
INFO 2023-09-09 19:06:44,445 basehttp 4568 23728 "GET /sem_4/post/1/ HTTP/1.1" 200 84458
INFO 2023-09-09 19:07:19,196 basehttp 4568 23728 "POST /sem_4/post/1/ HTTP/1.1" 302 0
INFO 2023-09-09 19:07:19,659 basehttp 4568 23728 "GET /sem_4/post/1/ HTTP/1.1" 200 84752
INFO 2023-09-09 19:07:27,949 basehttp 4568 23728 "GET /sem_3/author/3/ HTTP/1.1" 200 8559
INFO 2023-09-09 19:07:29,771 basehttp 4568 23728 "GET /sem_4/post/13/ HTTP/1.1" 200 79030
